### ISSUE TITLE
Preminor doesn't increment pre-counter

### ISSUE THREAD

**Issue by ross-nordstrom** [phuu/npm-release#4]
If you are at version `v0.1.0-0`, I expect `npm-release preminor` to bump it to `v0.1.0-1`, but instead it bumps it to `v0.2.0-0`. Am I using the wrong command?

**Comment by evanplaice** [comment]
That looks to be working as expected.

A pre-releases are the same as release candidates. They denote releases that require further testing/verification before they're ready for production. In your case, `v0.2.0-0` needs to be cleared before the code is officially released to production as `v0.2.0`.

**Comment by ross-nordstrom** [comment]
Hmm, I guess I can't argue it, since that's what `semver` does.

However, my intuition would have been that repeatedly doing a `preminor` bump would be more idempotent and simply increment the `preid`. 

```sh
$ semver v0.0.0 -i preminor 
0.1.0-0
$ semver v0.1.0-0 -i preminor 
0.2.0-0
$ semver v0.2.0-0 -i preminor 
0.3.0-0
```

```sh
$ semver --help
SemVer 5.1.0
```

I think I understand `preminor` now. In hindsight, what I was looking for is something like `semver`'s `prerelease`:

```sh
$ semver v0.0.0 -i prerelease
0.0.1-0
$ semver v0.0.1-0 -i prerelease
0.0.1-1
$ semver v0.0.1-1 -i prerelease
0.0.1-2
```


Anyways, thanks for responding to this. I'll go ahead and close since it was my misunderstanding.

**Comment by evanplaice** [comment]
@ross-nordstrom I'd expect it to work like prerelease too.

@phuu  is this a bug?

**Comment by phuu** [comment]
Hey @ross-nordstrom & @evanplaice. Looks to me like `prerelease` works as expected. `npm-release` uses `npm version` under the hood and `npm version prerelease` seems to do the right thing. Let me know if you're seeing something different.
